# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_research', '0002_auto_20190905_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game_stats',
            name='points_allowed_by_defense_special_teams',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
