# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_research', '0003_auto_20190905_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='all_names',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
