# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_research', '0004_auto_20190905_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='field_goal_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='intended_touch_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_completion_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_yards_per_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='quarterback_hit_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_yards_per_reception',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_yards_per_target',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='reception_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rush_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rushing_yards_per_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='sack_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='snaps_played_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='tackle_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='target_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='total_tackles',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='touch_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
