# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-07 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_research', '0005_auto_20190907_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fantasy_position',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='assisted_tackles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='defensive_touchdowns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='extra_points_attempted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='extra_points_made',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_point_snap_percentage_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_draft_kings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_fan_duel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_fantasy_draft',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_half_point_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_per_game_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_ppr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_six_point_pass_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fantasy_points_yahoo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='field_goal_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='field_goals_attempted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='field_goals_longest_made',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='field_goals_made',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fumbles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fumbles_forced',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fumbles_lost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='fumbles_recovered',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='intended_touch_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='interceptions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passes_defended',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_attempts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_completion_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_completions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_interceptions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_touchdowns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_yards',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='passing_yards_per_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='quarterback_hit_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='quarterback_hits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_long',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_targets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_touchdowns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_yards',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_yards_per_reception',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receiving_yards_per_target',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='reception_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='receptions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rush_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rushing_attempts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rushing_touchdowns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rushing_yards',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='rushing_yards_per_attempt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='sack_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='sack_yards',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='sacks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='safeties',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='snaps_per_game',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='snaps_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='snaps_played_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='solo_tackles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='special_teams_touchdowns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='tackle_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='tackles_for_loss',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='target_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='total_tackles',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='player_game_stats',
            name='touch_snap_percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
    ]
