# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_research', '0006_auto_20190907_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season_type',
            field=models.CharField(default='REG', max_length=4, null=True),
        ),
    ]
